### PR TITLE
Refactor register machine

### PR DESCRIPTION
**Pull request by tigertv**
Refactor the decode function in the register machine interpreter.
The following is faster.

### CODE REVIEW

**Comment by vkazanov** [comment]
Why do you this it's gonna be faster? Besides I'd go for readability here anyways and let the compiler extract the common subexpression.

**Comment by tigertv** [comment]
I just compiled it. The code is shorter
Before:
```
08048910 <decode>:
 8048910:	8b 44 24 04          	mov    eax,DWORD PTR [esp+0x4]
 8048914:	8b 54 24 08          	mov    edx,DWORD PTR [esp+0x8]
 8048918:	89 c1                	mov    ecx,eax
 804891a:	66 c1 e9 0c          	shr    cx,0xc
 804891e:	88 0a                	mov    BYTE PTR [edx],cl
 8048920:	8b 4c 24 0c          	mov    ecx,DWORD PTR [esp+0xc]
 8048924:	89 c2                	mov    edx,eax
 8048926:	81 e2 00 0f 00 00    	and    edx,0xf00
 804892c:	c1 fa 08             	sar    edx,0x8
 804892f:	88 11                	mov    BYTE PTR [ecx],dl
 8048931:	8b 4c 24 10          	mov    ecx,DWORD PTR [esp+0x10]
 8048935:	89 c2                	mov    edx,eax
 8048937:	81 e2 f0 00 00 00    	and    edx,0xf0
 804893d:	c1 fa 04             	sar    edx,0x4
 8048940:	88 11                	mov    BYTE PTR [ecx],dl
 8048942:	8b 54 24 14          	mov    edx,DWORD PTR [esp+0x14]
 8048946:	89 c1                	mov    ecx,eax
 8048948:	83 e1 0f             	and    ecx,0xf
 804894b:	88 0a                	mov    BYTE PTR [edx],cl
 804894d:	8b 54 24 18          	mov    edx,DWORD PTR [esp+0x18]
 8048951:	88 02                	mov    BYTE PTR [edx],al
 8048953:	c3                   	ret    
 8048954:	8d b6 00 00 00 00    	lea    esi,[esi+0x0]
 804895a:	8d bf 00 00 00 00    	lea    edi,[edi+0x0]

08048960 <vm_interpret>:
 8048960:	55                   	push   ebp

```
after:
```
08048910 <decode>:
 8048910:	8b 44 24 04          	mov    eax,DWORD PTR [esp+0x4]
 8048914:	8b 54 24 18          	mov    edx,DWORD PTR [esp+0x18]
 8048918:	88 02                	mov    BYTE PTR [edx],al
 804891a:	8b 54 24 14          	mov    edx,DWORD PTR [esp+0x14]
 804891e:	89 c1                	mov    ecx,eax
 8048920:	83 e1 0f             	and    ecx,0xf
 8048923:	88 0a                	mov    BYTE PTR [edx],cl
 8048925:	89 c2                	mov    edx,eax
 8048927:	8b 4c 24 10          	mov    ecx,DWORD PTR [esp+0x10]
 804892b:	66 c1 ea 04          	shr    dx,0x4
 804892f:	83 e2 0f             	and    edx,0xf
 8048932:	88 11                	mov    BYTE PTR [ecx],dl
 8048934:	89 c2                	mov    edx,eax
 8048936:	8b 4c 24 0c          	mov    ecx,DWORD PTR [esp+0xc]
 804893a:	66 c1 ea 08          	shr    dx,0x8
 804893e:	66 c1 e8 0c          	shr    ax,0xc
 8048942:	83 e2 0f             	and    edx,0xf
 8048945:	88 11                	mov    BYTE PTR [ecx],dl
 8048947:	8b 54 24 08          	mov    edx,DWORD PTR [esp+0x8]
 804894b:	88 02                	mov    BYTE PTR [edx],al
 804894d:	c3                   	ret    
 804894e:	66 90                	xchg   ax,ax

08048950 <vm_interpret>:
 8048950:	55                   	push   ebp

```

`8048937:	81 e2 f0 00 00 00    	and    edx,0xf0`
takes 6 bytes
`8048948:	83 e1 0f             	and    ecx,0xf`
takes 3 bytes

**Comment by vkazanov** [comment]
Shorter - yes, but is it faster? There's some profiling code, you could use it to measure the difference to make sure it makes sense to complicate the code. Also, which compiler do you use?

What I am saying is that sometimes it makes sense to keep the code readable.

**Comment by tigertv** [comment]
I used gcc, options from Makefile. If you think it is not usefull, not readable, so let's close the PR.

**Comment by vkazanov** [comment]
Well. You do assignment inline (`>>=`). That's might be a bit confusing. 

But if it makes measurable difference - I don't mind it at all. After all, the point of those blog posts was to see how performant bytecode interpreters might be implemented.

**Comment by tigertv** [comment]
OK.)

**Pull request closed without merging**
